//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HikDownloader.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HikDownloader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comedor.
        /// </summary>
        internal static string Channel1 {
            get {
                return ResourceManager.GetString("Channel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CCM 4 y 8.
        /// </summary>
        internal static string Channel10 {
            get {
                return ResourceManager.GetString("Channel10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Kase 1.
        /// </summary>
        internal static string Channel11 {
            get {
                return ResourceManager.GetString("Channel11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SFM 4 - BTA 1.
        /// </summary>
        internal static string Channel12 {
            get {
                return ResourceManager.GetString("Channel12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calle fumadero.
        /// </summary>
        internal static string Channel13 {
            get {
                return ResourceManager.GetString("Channel13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acceso Portería.
        /// </summary>
        internal static string Channel14 {
            get {
                return ResourceManager.GetString("Channel14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sector lubricantes.
        /// </summary>
        internal static string Channel15 {
            get {
                return ResourceManager.GetString("Channel15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cámara 16.
        /// </summary>
        internal static string Channel16 {
            get {
                return ResourceManager.GetString("Channel16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desco.
        /// </summary>
        internal static string Channel2 {
            get {
                return ResourceManager.GetString("Channel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Playa de carga.
        /// </summary>
        internal static string Channel3 {
            get {
                return ResourceManager.GetString("Channel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Taller Mantenimiento.
        /// </summary>
        internal static string Channel4 {
            get {
                return ResourceManager.GetString("Channel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Playa de carga.
        /// </summary>
        internal static string Channel5 {
            get {
                return ResourceManager.GetString("Channel5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Producto en tránsito.
        /// </summary>
        internal static string Channel6 {
            get {
                return ResourceManager.GetString("Channel6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lugar de estibas.
        /// </summary>
        internal static string Channel7 {
            get {
                return ResourceManager.GetString("Channel7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CCM 1 y CCM 3.
        /// </summary>
        internal static string Channel8 {
            get {
                return ResourceManager.GetString("Channel8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CCM 7, 8 y 9.
        /// </summary>
        internal static string Channel9 {
            get {
                return ResourceManager.GetString("Channel9", resourceCulture);
            }
        }
    }
}
